Fix compiling error with rtt-5.0
RT-Thread-packages/netutils pull request #92
Opened 2023-05-15 13:30 UTC by helloeagleyang

- Fixed compiling error when enabling LOG with rt-thread 5.0

2023-05-15 22:09 UTC, mysterywolf requested changes

2023-05-15 22:09 UTC, mysterywolf commented on iperf/iperf.c
> +
请使用 `#if RT_VER_NUM >= 0x50000` 判断

2023-05-16 01:33 UTC, mysterywolf approved these changes

2023-05-16 01:34 UTC, merged

2023-05-16 05:04 UTC, armink commented
@mysterywolf 有没有办法把所有软件包都测试一遍？